window.BrieflySeed = {
  markets: [
    {
      code: "BG",
      label: "България",
      locale: "bg-BG",
      language: "Bulgarian",
      timezone: "Europe/Sofia",
      tagline: "Всичко важно за деня. Накратко.",
      dailyTitle: "Ето най-важното за днес",
      summaryLabel: "Накратко",
      whatThisMeansLabel: "Какво означава това за мен?",
      insufficientInfo:
        "Няма достатъчно информация в наличните източници, за да отговоря уверено.",
      profileOptions: [
        "служител",
        "самонает",
        "собственик на бизнес",
        "родител",
        "студент",
        "пенсионер",
        "шофьор",
        "собственик на имот",
      ],
    },
    {
      code: "RS",
      label: "Srbija",
      locale: "sr-RS",
      language: "Serbian",
      timezone: "Europe/Belgrade",
      script: "Latin",
      tagline: "Sve važno za dan. Ukratko.",
      dailyTitle: "Ovo je najvažnije danas",
      summaryLabel: "Ukratko",
      whatThisMeansLabel: "Šta ovo znači za mene?",
      insufficientInfo:
        "Nema dovoljno informacija u dostupnim izvorima da odgovorim pouzdano.",
      profileOptions: [
        "zaposlen",
        "preduzetnik",
        "vlasnik biznisa",
        "roditelj",
        "student",
        "penzioner",
        "vozač",
        "vlasnik nekretnine",
      ],
    },
  ],
  ui: {
    BG: {
      marketLabel: "Пазар",
      tabHome: "Днес",
      tabBrief: "Бриф",
      tabSources: "Източници",
      tabEditorial: "Редакция",
      tabStudio: "AI Studio",
      storiesLabel: "истории",
      minutesLabel: "минути",
      completedLabel: "завършени",
      startBrief: "Започни днешния бриф",
      continueBrief: "Продължи",
      personalEyebrow: "За теб",
      personalTitle: "Направи Briefly по-полезен за теб",
      personalCopy: "Избери няколко контекста за по-релевантни обяснения.",
      editProfile: "Настрой",
      profileLegend: "Моят контекст",
      deleteProfile: "Изтрий",
      saveProfile: "Запази",
      previous: "Предишна",
      next: "Следваща",
      completedTitle: "Брифът е завършен",
      completedCopy: "Запази важните истории или започни отначало, когато искаш.",
      restart: "Започни отначало",
      sourcesEyebrow: "Източници",
      sourcesTitle: "Конфигурируеми записи",
      sourceName: "Име",
      sourceCategory: "Категория",
      addSource: "Добави",
      editorialTitle: "Редакционна основа",
      architectureTitle: "Архитектура",
      decisionsTitle: "Нужни решения",
      schemaTitle: "Данни",
      studioTitle: "Социално съдържание",
      selectStory: "История",
      whyItMatters: "Защо е важно",
      openFull: "Отвори",
      storyPosition: "История",
      of: "от",
      sampleBadge: "Seed data",
      sourceCount: "източника",
      oneSource: "източник",
      saved: "Запазено",
      save: "Запази",
      share: "Сподели",
      copied: "Текстът е подготвен",
      noFeed: "RSS не е потвърден",
      active: "Активен",
      inactive: "Неактивен",
      official: "Официален източник",
      requiredVerification: "изисква проверка",
      studioSlide: "Слайд",
      studioCaption: "Текст за публикация",
      disclaimer:
        "Това е обяснителна информация, не правен, данъчен, медицински или финансов съвет.",
    },
    RS: {
      marketLabel: "Tržište",
      tabHome: "Danas",
      tabBrief: "Brif",
      tabSources: "Izvori",
      tabEditorial: "Redakcija",
      tabStudio: "AI Studio",
      storiesLabel: "priča",
      minutesLabel: "minuta",
      completedLabel: "završeno",
      startBrief: "Počni današnji brif",
      continueBrief: "Nastavi",
      personalEyebrow: "Za tebe",
      personalTitle: "Učini Briefly korisnijim",
      personalCopy: "Izaberi nekoliko konteksta za relevantnija objašnjenja.",
      editProfile: "Podesi",
      profileLegend: "Moj kontekst",
      deleteProfile: "Obriši",
      saveProfile: "Sačuvaj",
      previous: "Prethodna",
      next: "Sledeća",
      completedTitle: "Brif je završen",
      completedCopy: "Sačuvaj važne priče ili kreni ponovo kad želiš.",
      restart: "Počni ponovo",
      sourcesEyebrow: "Izvori",
      sourcesTitle: "Konfigurabilni zapisi",
      sourceName: "Ime",
      sourceCategory: "Kategorija",
      addSource: "Dodaj",
      editorialTitle: "Redakcijska osnova",
      architectureTitle: "Arhitektura",
      decisionsTitle: "Potrebne odluke",
      schemaTitle: "Podaci",
      studioTitle: "Društveni sadržaj",
      selectStory: "Priča",
      whyItMatters: "Zašto je važno",
      openFull: "Otvori",
      storyPosition: "Priča",
      of: "od",
      sampleBadge: "Seed data",
      sourceCount: "izvora",
      oneSource: "izvor",
      saved: "Sačuvano",
      save: "Sačuvaj",
      share: "Podeli",
      copied: "Tekst je pripremljen",
      noFeed: "RSS nije potvrđen",
      active: "Aktivan",
      inactive: "Neaktivan",
      official: "Zvanični izvor",
      requiredVerification: "potrebna provera",
      studioSlide: "Slajd",
      studioCaption: "Tekst objave",
      disclaimer:
        "Ovo je informativno objašnjenje, ne pravni, poreski, medicinski ili finansijski savet.",
    },
  },
  dailyBriefs: {
    BG: {
      market: "BG",
      date: "2026-07-24",
      estimatedMinutes: 5,
      stories: [
        {
          id: "bg-demo-public-transport",
          category: "Общество",
          headline: "Демо история: нов график за градски транспорт",
          description:
            "Примерен клъстер показва как Briefly би обяснил промяна, която засяга ежедневното придвижване.",
          keyPoints: [
            "Промяната е маркирана като примерна, не като реална новина.",
            "Клъстерът събира няколко източника в една кратка история.",
            "Потребителят вижда практично значение според профила си.",
          ],
          whyItMatters:
            "Този формат показва как важна обществена промяна може да бъде завършима за четене за под минута.",
          next:
            "В реалната система редактор потвърждава източниците, срока и засегнатите групи.",
          meansForMe: {
            "служител": "Провери дали обичайният ти маршрут или час на пътуване се променя.",
            "собственик на бизнес":
              "Ако екипът ти пътува през засегнат район, може да има нужда от оперативна бележка.",
            default:
              "Няма достатъчно личен контекст за конкретно действие, но историята би била релевантна за хора, които пътуват ежедневно.",
          },
          sources: ["Demo Civic Bulletin", "Demo Transport Desk"],
          sourceCount: 2,
          updatedAt: "2026-07-24T08:10:00+03:00",
          image: "./assets/bg-transport.png",
          sample: true,
        },
        {
          id: "bg-demo-tax-deadline",
          category: "Икономика",
          headline: "Демо история: срок за електронна декларация",
          description:
            "Пример за официална информация, при която Briefly отделя фактите от тълкуването.",
          keyPoints: [
            "Официалният линк остава видим до обяснението.",
            "Системата показва кой е засегнат и кога има действие.",
            "AI отговорите са ограничени до свързаните източници.",
          ],
          whyItMatters:
            "Срокове и административни промени често имат реална цена за граждани и малък бизнес.",
          next: "Нужни са потвърдени официални източници преди публикуване.",
          meansForMe: {
            "самонает": "Може да има срок, който трябва да провериш в официалния източник.",
            "собственик на бизнес":
              "В реална история Briefly би показал срокове, документи и засегнати дейности.",
            default:
              "Няма достатъчно информация за персонално действие без потвърден официален източник.",
          },
          sources: ["Demo Official Register"],
          sourceCount: 1,
          updatedAt: "2026-07-24T09:20:00+03:00",
          image: "./assets/bg-economy.png",
          official: true,
          sample: true,
        },
        {
          id: "bg-demo-energy",
          category: "Енергия",
          headline: "Демо история: решение за регулирани цени",
          description:
            "Кратка примерна история за промяна, която може да засегне домакинства и компании.",
          keyPoints: [
            "Историята пази разделение между факти, ефект и следващи стъпки.",
            "Важността се оценява на ниво клъстер, не на единична статия.",
            "Редактор може да промени класирането преди публикуване.",
          ],
          whyItMatters:
            "Енергийните решения могат да повлияят на семейни бюджети, бизнес разходи и инфлационни очаквания.",
          next: "Очаква се редакционна проверка на официалните документи.",
          meansForMe: {
            "собственик на имот": "Следи за промени в месечните разходи, ако историята бъде потвърдена.",
            "собственик на бизнес":
              "Може да има ефект върху оперативните разходи, но Briefly не дава финансов съвет.",
            default:
              "Ефектът зависи от договор, потребление и локация; нужни са потвърдени данни.",
          },
          sources: ["Demo Energy Monitor", "Demo Official Register"],
          sourceCount: 2,
          updatedAt: "2026-07-24T10:05:00+03:00",
          image: "./assets/bg-energy.png",
          sample: true,
        },
        {
          id: "bg-demo-health",
          category: "Здраве",
          headline: "Демо история: препоръка за обществено здраве",
          description:
            "Примерен формат за ясно разграничаване между препоръка, риск и източник.",
          keyPoints: [
            "Не се представя медицински съвет като персонална инструкция.",
            "Показват се само твърдения с източник.",
            "При липса на данни системата отказва категоричен отговор.",
          ],
          whyItMatters:
            "Общественото здраве изисква особено внимателен тон и видима връзка към първични източници.",
          next: "Нужен е протокол за проверка на медицински и институционални източници.",
          meansForMe: {
            "родител": "Провери официалния източник, преди да променяш здравно поведение.",
            "пенсионер": "Не предприемай действие само по резюме; потърси официална информация.",
            default:
              "Няма достатъчно информация за персонална препоръка. Това не е медицински съвет.",
          },
          sources: ["Demo Public Health Source"],
          sourceCount: 1,
          updatedAt: "2026-07-24T10:35:00+03:00",
          image: "./assets/bg-health.png",
          sample: true,
        },
        {
          id: "bg-demo-education",
          category: "Образование",
          headline: "Демо история: промени в учебен календар",
          description:
            "Пример за история, при която родителите и учениците виждат различен практичен контекст.",
          keyPoints: [
            "Засегнатите аудитории се пазят като структурирани данни.",
            "Обяснението може да се персонализира без задължителен профил.",
            "Свързаните истории остават отделени по пазар.",
          ],
          whyItMatters:
            "Календарни промени засягат семейно планиране, училища и местни услуги.",
          next: "В реална версия източникът трябва да бъде официален и проверен.",
          meansForMe: {
            "родител": "Може да се наложи да провериш графика за грижа или пътуване.",
            "студент": "Проследи дали промяната важи за твоята институция.",
            default:
              "Историята може да е релевантна, ако имаш училищен или университетски график.",
          },
          sources: ["Demo Education Desk", "Demo Official Register"],
          sourceCount: 2,
          updatedAt: "2026-07-24T11:00:00+03:00",
          image: "./assets/bg-education.png",
          sample: true,
        },
        {
          id: "bg-demo-world",
          category: "Свят",
          headline: "Демо история: международно решение с регионален ефект",
          description:
            "Пример за това как Briefly отделя международната новина от местното значение.",
          keyPoints: [
            "Историята не влиза в брифа само защото е шумна.",
            "Класирането гледа последици, спешност и надеждност на източниците.",
            "Пазарите остават разделени дори при сходна международна тема.",
          ],
          whyItMatters:
            "Международни решения могат да имат местен ефект върху цени, правила или сигурност.",
          next: "Редактор проверява дали има достатъчен местен ефект за дневния бриф.",
          meansForMe: {
            "инвеститор": "Не вземай инвестиционно решение само по кратко обяснение.",
            "собственик на бизнес":
              "Следи дали има ефект върху доставки, регулации или търсене.",
            default:
              "Местният ефект зависи от сектор и локация; нужни са повече източници.",
          },
          sources: ["Demo World Wire", "Demo Regional Desk"],
          sourceCount: 2,
          updatedAt: "2026-07-24T11:30:00+03:00",
          image: "./assets/bg-world.png",
          sample: true,
        },
      ],
    },
    RS: {
      market: "RS",
      date: "2026-07-24",
      estimatedMinutes: 5,
      stories: [
        {
          id: "rs-demo-transport",
          category: "Društvo",
          headline: "Demo priča: novi režim javnog prevoza",
          description:
            "Primer klastera pokazuje kako Briefly objašnjava promenu koja utiče na svakodnevno kretanje.",
          keyPoints: [
            "Promena je označena kao primer, ne kao stvarna vest.",
            "Klaster spaja više izvora u jednu kratku priču.",
            "Korisnik vidi praktično značenje prema profilu.",
          ],
          whyItMatters:
            "Format pokazuje kako važna javna promena može da se pročita za manje od minuta.",
          next: "U stvarnoj verziji urednik potvrđuje izvore, rok i pogođene grupe.",
          meansForMe: {
            zaposlen: "Proveri da li se menja tvoja uobičajena ruta ili vreme putovanja.",
            "vlasnik biznisa":
              "Ako tim putuje kroz pogođen deo grada, možda je potrebna kratka interna napomena.",
            default:
              "Nema dovoljno ličnog konteksta za konkretan korak, ali priča može biti relevantna za svakodnevne putnike.",
          },
          sources: ["Demo Civic Bulletin", "Demo Transport Desk"],
          sourceCount: 2,
          updatedAt: "2026-07-24T08:10:00+02:00",
          image: "./assets/rs-transport.png",
          sample: true,
        },
        {
          id: "rs-demo-tax",
          category: "Ekonomija",
          headline: "Demo priča: rok za elektronsku prijavu",
          description:
            "Primer zvanične informacije gde Briefly razdvaja činjenice od tumačenja.",
          keyPoints: [
            "Zvanični link ostaje vidljiv pored objašnjenja.",
            "Sistem prikazuje ko je pogođen i kada postoji radnja.",
            "AI odgovori su ograničeni na povezane izvore.",
          ],
          whyItMatters:
            "Rokovi i administrativne promene često imaju realnu cenu za građane i mala preduzeća.",
          next: "Potrebni su potvrđeni zvanični izvori pre objave.",
          meansForMe: {
            preduzetnik: "Može postojati rok koji treba proveriti u zvaničnom izvoru.",
            "vlasnik biznisa":
              "U stvarnoj priči Briefly bi prikazao rokove, dokumente i pogođene delatnosti.",
            default:
              "Nema dovoljno informacija za ličnu radnju bez potvrđenog zvaničnog izvora.",
          },
          sources: ["Demo Official Register"],
          sourceCount: 1,
          updatedAt: "2026-07-24T09:20:00+02:00",
          image: "./assets/rs-economy.png",
          official: true,
          sample: true,
        },
        {
          id: "rs-demo-energy",
          category: "Energija",
          headline: "Demo priča: odluka o regulisanim cenama",
          description:
            "Kratka primer priča o promeni koja može uticati na domaćinstva i kompanije.",
          keyPoints: [
            "Priča čuva razliku između činjenica, efekta i narednih koraka.",
            "Važnost se procenjuje na nivou klastera.",
            "Urednik može promeniti rang pre objave.",
          ],
          whyItMatters:
            "Energetske odluke mogu uticati na porodične budžete, troškove poslovanja i inflaciju.",
          next: "Očekuje se urednička provera zvaničnih dokumenata.",
          meansForMe: {
            "vlasnik nekretnine": "Prati moguće promene mesečnih troškova ako priča bude potvrđena.",
            "vlasnik biznisa":
              "Može postojati efekat na operativne troškove, ali Briefly ne daje finansijski savet.",
            default:
              "Efekat zavisi od ugovora, potrošnje i lokacije; potrebni su potvrđeni podaci.",
          },
          sources: ["Demo Energy Monitor", "Demo Official Register"],
          sourceCount: 2,
          updatedAt: "2026-07-24T10:05:00+02:00",
          image: "./assets/rs-energy.png",
          sample: true,
        },
        {
          id: "rs-demo-health",
          category: "Zdravlje",
          headline: "Demo priča: preporuka za javno zdravlje",
          description:
            "Primer formata za jasno razdvajanje preporuke, rizika i izvora.",
          keyPoints: [
            "Medicinska informacija se ne prikazuje kao lično uputstvo.",
            "Prikazuju se samo tvrdnje uz izvor.",
            "Ako nema podataka, sistem odbija siguran odgovor.",
          ],
          whyItMatters:
            "Javno zdravlje traži posebno pažljiv ton i vidljivu vezu ka primarnim izvorima.",
          next: "Potreban je protokol za proveru medicinskih i institucionalnih izvora.",
          meansForMe: {
            roditelj: "Proveri zvanični izvor pre promene zdravstvenog ponašanja.",
            penzioner: "Ne preduzimaj radnju samo na osnovu sažetka; potraži zvaničnu informaciju.",
            default:
              "Nema dovoljno informacija za ličnu preporuku. Ovo nije medicinski savet.",
          },
          sources: ["Demo Public Health Source"],
          sourceCount: 1,
          updatedAt: "2026-07-24T10:35:00+02:00",
          image: "./assets/rs-health.png",
          sample: true,
        },
        {
          id: "rs-demo-education",
          category: "Obrazovanje",
          headline: "Demo priča: izmene školskog kalendara",
          description:
            "Primer priče gde roditelji i studenti dobijaju različit praktičan kontekst.",
          keyPoints: [
            "Pogođene publike se čuvaju kao strukturirani podaci.",
            "Objašnjenje se personalizuje bez obaveznog profila.",
            "Povezane priče ostaju razdvojene po tržištu.",
          ],
          whyItMatters:
            "Promene kalendara utiču na porodično planiranje, škole i lokalne usluge.",
          next: "U stvarnoj verziji izvor mora biti zvaničan i potvrđen.",
          meansForMe: {
            roditelj: "Možda treba proveriti raspored čuvanja dece ili putovanja.",
            student: "Proveri da li promena važi za tvoju instituciju.",
            default:
              "Priča može biti relevantna ako imaš školski ili univerzitetski raspored.",
          },
          sources: ["Demo Education Desk", "Demo Official Register"],
          sourceCount: 2,
          updatedAt: "2026-07-24T11:00:00+02:00",
          image: "./assets/rs-education.png",
          sample: true,
        },
        {
          id: "rs-demo-world",
          category: "Svet",
          headline: "Demo priča: međunarodna odluka sa regionalnim efektom",
          description:
            "Primer kako Briefly odvaja međunarodnu vest od lokalnog značaja.",
          keyPoints: [
            "Priča ne ulazi u brif samo zato što je glasna.",
            "Rangiranje gleda posledice, hitnost i pouzdanost izvora.",
            "Tržišta ostaju odvojena i kod slične međunarodne teme.",
          ],
          whyItMatters:
            "Međunarodne odluke mogu imati lokalni efekat na cene, pravila ili bezbednost.",
          next: "Urednik proverava da li postoji dovoljan lokalni značaj za dnevni brif.",
          meansForMe: {
            "vlasnik biznisa": "Prati da li ima efekta na dobavljače, regulaciju ili potražnju.",
            default:
              "Lokalni efekat zavisi od sektora i lokacije; potrebno je više izvora.",
          },
          sources: ["Demo World Wire", "Demo Regional Desk"],
          sourceCount: 2,
          updatedAt: "2026-07-24T11:30:00+02:00",
          image: "./assets/rs-world.png",
          sample: true,
        },
      ],
    },
  },
  sources: [
    { market: "BG", name: "BTA", websiteUrl: "https://www.bta.bg", feedUrl: null, type: "rss", language: "Bulgarian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "BG", name: "Capital", websiteUrl: "https://www.capital.bg", feedUrl: null, type: "rss", language: "Bulgarian", category: "business", active: false, verificationStatus: "requires_verification" },
    { market: "BG", name: "Dnevnik", websiteUrl: "https://www.dnevnik.bg", feedUrl: null, type: "rss", language: "Bulgarian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "BG", name: "BNT", websiteUrl: "https://bntnews.bg", feedUrl: null, type: "rss", language: "Bulgarian", category: "public_media", active: false, verificationStatus: "requires_verification" },
    { market: "BG", name: "BBC World", websiteUrl: "https://www.bbc.com/news/world", feedUrl: null, type: "rss", language: "English", category: "world", active: false, verificationStatus: "requires_verification" },
    { market: "BG", name: "National Assembly", websiteUrl: "https://www.parliament.bg", feedUrl: null, type: "official", language: "Bulgarian", category: "government", active: false, official: true, verificationStatus: "requires_verification" },
    { market: "BG", name: "Council of Ministers", websiteUrl: "https://www.gov.bg", feedUrl: null, type: "official", language: "Bulgarian", category: "government", active: false, official: true, verificationStatus: "requires_verification" },
    { market: "BG", name: "National Revenue Agency", websiteUrl: "https://nra.bg", feedUrl: null, type: "official", language: "Bulgarian", category: "government", active: false, official: true, verificationStatus: "requires_verification" },
    { market: "BG", name: "Bulgarian National Bank", websiteUrl: "https://www.bnb.bg", feedUrl: null, type: "official", language: "Bulgarian", category: "government", active: false, official: true, verificationStatus: "requires_verification" },
    { market: "RS", name: "Tanjug", websiteUrl: "https://www.tanjug.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "RTS", websiteUrl: "https://www.rts.rs", feedUrl: null, type: "rss", language: "Serbian", category: "public_media", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "B92", websiteUrl: "https://www.b92.net", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Blic", websiteUrl: "https://www.blic.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Danas", websiteUrl: "https://www.danas.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Kurir", websiteUrl: "https://www.kurir.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Mondo", websiteUrl: "https://mondo.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "N1 Srbija", websiteUrl: "https://n1info.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Nova.rs", websiteUrl: "https://nova.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Politika", websiteUrl: "https://www.politika.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Telegraf.rs", websiteUrl: "https://www.telegraf.rs", feedUrl: null, type: "rss", language: "Serbian", category: "general", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Južne Vesti", websiteUrl: "https://www.juznevesti.com", feedUrl: null, type: "rss", language: "Serbian", category: "regional", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "Vreme", websiteUrl: "https://www.vreme.com", feedUrl: null, type: "rss", language: "Serbian", category: "analysis", active: false, verificationStatus: "requires_verification" },
    { market: "RS", name: "RTV Vojvodina", websiteUrl: "https://www.rtv.rs", feedUrl: null, type: "rss", language: "Serbian", category: "public_media", active: false, verificationStatus: "requires_verification" },
  ],
  architecture: [
    "Final stack: Next.js, TypeScript, React, Tailwind, Supabase PostgreSQL, Supabase Auth and Storage.",
    "Server routes own ingestion, OpenAI calls, ranking, Q&A and social generation.",
    "Markets, sources, clusters, briefs and generated content remain separated by market.",
    "All API keys stay server-side; the browser only receives approved story payloads.",
  ],
  decisions: [
    "OpenAI API key and model policy for summaries, ranking, Q&A and social outputs.",
    "Supabase project URL, anon key, service role key and storage bucket names.",
    "Verified RSS or official URLs for each source before activation.",
    "Editorial access model for protected workspace routes.",
    "Analytics provider choice, or continue with the local abstraction.",
  ],
  schemaTables: [
    "markets",
    "users",
    "user_profiles",
    "interests",
    "user_interests",
    "sources",
    "raw_articles",
    "story_clusters",
    "story_sources",
    "daily_briefs",
    "daily_brief_stories",
    "saved_stories",
    "ai_conversations",
    "ai_messages",
    "generated_social_content",
    "publishing_queue",
    "ingestion_logs",
    "ranking_logs",
  ],
};
